kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4   # kind website  kind cluster api version
name: om-deshmukh-cluster  # cluster name

nodes:

- role: control-plane
  image: kindest/node:v1.24.0 #docker node image


- role: worker
  image: kindest/node:v1.24.0


- role: worker
  image: kindest/node:v1.24.0


- role: worker
  image: kindest/node:v1.24.0